#
# Software Name : free5gc-helm
# SPDX-FileCopyrightText: Copyright (c) 2021 Orange
# SPDX-License-Identifier: Apache-2.0
#
# This software is distributed under the Apache License 2.0,
# the text of which is available at https://github.com/Orange-OpenSource/towards5gs-helm/blob/main/LICENSE
# or see the "LICENSE" file for more details.
#
# Author: Adapted for NWDAF
# Software description: An open-source project providing Helm charts to deploy 5G components (Core + RAN) on top of Kubernetes
#
{{- with .Values.nwdaf }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configmap.name }}
  labels:
    {{- include "free5gc-nwdaf.labels" $ | nindent 4 }}
data:
  nwdafcfg.yaml: |
    info:
      version: 1.0.0
      description: NWDAF initial configuration

    configuration:
      nwdafName: NWDAF
      sbi:
        scheme: {{ $.Values.global.sbi.scheme }}
        registerIPv4: {{ .service.name }}
        bindingIPv4: 0.0.0.0
        port: {{ .service.targetPort }}
      serviceNameList:
        - nnwdaf-eventssubscription
        - nnwdaf-analyticsinfo
      nrfUri: {{ $.Values.global.sbi.scheme }}://{{ $.Values.global.nrf.service.name }}:{{ $.Values.global.nrf.service.port }}
      plmnList:
        - mcc: "208"
          mnc: "93"
      analyticsDelay: 30
      dataCollection:
        enabled: true
        collectionPeriod: 60
        targetNFs:
          - AMF
          - SMF
          - UPF

    logger:
      level: {{ .configuration.logger.level }}
{{- end }}
